// Taxonomia inicial de categorias, uma única vez na vida do BD (seed). Os ids
// aqui são os mesmos códigos numéricos que o fotop.com.br usa (id_estacoes) —
// mantidos de propósito como o Categoria.id local (não autoincrement livre),
// porque frontend/src/styles/fi-estacao.css tem uma fonte de ícones fixa
// nesses números (fi-estacao-{id}). Isso também faz o mapeamento
// categorias_provedores do Fotop ser trivial (identidade) — ver seed.ts.
export interface CategoriaSeedItem {
  id: number;
  slug: string;
  nome: string;
}

export const CATEGORIA_SEED_DATA: CategoriaSeedItem[] = [
  { id: 1, slug: 'corridaderua', nome: 'Corrida de rua' },
  { id: 22, slug: 'treinos', nome: 'Treinos' },
  { id: 3, slug: 'futebol', nome: 'Futebol' },
  { id: 4, slug: 'ciclismo', nome: 'Ciclismo' },
  { id: 11, slug: 'triathlon', nome: 'Duathlon / Triathlon' },
  { id: 18, slug: 'corridatrail', nome: 'Corrida de montanha' },
  { id: 77, slug: 'carnaval', nome: 'Carnaval' },
  { id: 78, slug: 'show-festival', nome: 'Show / Festival' },
  { id: 24, slug: 'acampamentos', nome: 'Acampamentos' },
  { id: 26, slug: 'beachtennis', nome: 'Beach Tênis' },
  { id: 27, slug: 'crossfit', nome: 'Crossfit' },
  { id: 12, slug: 'artemarcial', nome: 'Arte Marcial' },
  { id: 17, slug: 'esportesamotor', nome: 'Esportes a motor' },
  { id: 20, slug: 'turismo', nome: 'Turismo' },
  { id: 23, slug: 'Formatura', nome: 'Formatura' },
  { id: 19, slug: 'escolar', nome: 'Escolar' },
  { id: 13, slug: 'eventosocial', nome: 'Evento Social' },
  { id: 14, slug: 'ensaio', nome: 'Ensaio' },
  { id: 28, slug: 'futevolei', nome: 'Futevôlei' },
  { id: 33, slug: 'natacao', nome: 'Natação' },
  { id: 39, slug: 'esportesaquaticos', nome: 'Esportes Aquáticos' },
  { id: 41, slug: 'corridaobstaculos', nome: 'Corrida de Obstáculos' },
  { id: 25, slug: 'basquete', nome: 'Basquete' },
  { id: 9, slug: 'tenis', nome: 'Tenis' },
  { id: 36, slug: 'handball', nome: 'Handebol' },
  { id: 32, slug: 'hipismo', nome: 'Hipismo' },
  { id: 31, slug: 'golfe', nome: 'Golfe' },
  { id: 40, slug: 'padel', nome: 'Padel' },
  { id: 2, slug: 'rally', nome: 'Rally' },
  { id: 37, slug: 'rugby', nome: 'Rugby' },
  { id: 16, slug: 'surf', nome: 'Surf' },
  { id: 34, slug: 'volei', nome: 'Vôlei' },
  { id: 35, slug: 'baseball', nome: 'Baseball' },
  { id: 30, slug: 'ginasticaartistica', nome: 'Ginástica Artística' },
  { id: 38, slug: 'futebolamericano', nome: 'Futebol Americano' },
  { id: 42, slug: 'airsoft', nome: 'AirSoft' },
  { id: 43, slug: 'atletismo', nome: 'Atletismo' },
  { id: 44, slug: 'badminton', nome: 'Badminton' },
  { id: 45, slug: 'beachsoccer', nome: 'Beach Soccer' },
  { id: 46, slug: 'canoagem', nome: 'Canoagem' },
  { id: 61, slug: 'capoeira', nome: 'Capoeira' },
  { id: 47, slug: 'danca', nome: 'Dança' },
  { id: 48, slug: 'equestre', nome: 'Equestre' },
  { id: 62, slug: 'fisiculturismo', nome: 'Fisiculturismo' },
  { id: 63, slug: 'futsal', nome: 'Futsal' },
  { id: 49, slug: 'hockey', nome: 'Hockey' },
  { id: 64, slug: 'iatismo', nome: 'Iatismo' },
  { id: 50, slug: 'ioga', nome: 'Ioga' },
  { id: 65, slug: 'jiu-jítzu', nome: 'Jiu-jítzu' },
  { id: 66, slug: 'judo', nome: 'Judô' },
  { id: 67, slug: 'karate', nome: 'Karatê' },
  { id: 51, slug: 'kitesurf', nome: 'Kitesurf' },
  { id: 52, slug: 'mergulho', nome: 'Mergulho' },
  { id: 68, slug: 'motociclismo', nome: 'Motociclismo' },
  { id: 69, slug: 'motocros', nome: 'Motocros' },
  { id: 70, slug: 'muaythai', nome: 'Muay Thai' },
  { id: 53, slug: 'paintball', nome: 'Paintball' },
  { id: 72, slug: 'parapente', nome: 'Parapente' },
  { id: 71, slug: 'paraquedismo', nome: 'Paraquedismo' },
  { id: 54, slug: 'patinação', nome: 'Patinação' },
  { id: 55, slug: 'pescaria', nome: 'Pescaria' },
  { id: 73, slug: 'pets', nome: 'Pets' },
  { id: 56, slug: 'pickleball', nome: 'Pickleball' },
  { id: 57, slug: 'pilates', nome: 'Pilates' },
  { id: 74, slug: 'poloaquatico', nome: 'Polo aquático' },
  { id: 58, slug: 'rodeio', nome: 'Rodeio' },
  { id: 59, slug: 'skate', nome: 'Skate' },
  { id: 60, slug: 'tenisdemesa', nome: 'Tênis de mesa' },
  { id: 75, slug: 'xadrez', nome: 'Xadrez' },
  { id: 79, slug: 'hyrox', nome: 'Hyrox' },
  { id: 80, slug: 'moda', nome: 'Moda' },
  { id: 15, slug: 'outrosesportes', nome: 'Outros Esportes' },
  { id: 5, slug: 'outros', nome: 'Outros' },
];
